default: &default
  adapter : postgresql
  encoding: unicode
  pool    : 5
  timeout : 5000
  port    : 5432

test:
  <<      : *default
  host    : localhost
  database: acercar-ingenieria_test

development:
  <<      : *default
  host    : localhost
  database: acercar-ingenieria_development

production:
  <<      : *default
  host    : postgres_db
  database: acercar-ingenieria_production
  username: postgres
